config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get 'home/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Memiarnia', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Strona główna', root_path %></li>
            <li><%= link_to 'O mnie', home_about_path %></li>

            <% if user_signed_in? %>
              <li><%= link_to 'Edycja profilu', edit_user_registration_path %></li>
              <li><%= link_to 'Wyloguj', destroy_user_session_path, method: :destroy %></li>
            <% else %>
              <li><%= link_to 'Logowanie', new_user_session_path %></li>
              <li><%= link_to 'Rejestracja', new_user_registration_path %></li>
            <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/about.html.erb
<div class="jumbotron">
<h1>O mnie...</h1>
<p>Z tej strony Maciej Szytów - pan i władca tego czegoś</p>
  <%= link_to 'Strona główna', root_path, class: 'btn btn-primary' %>
  <%= link_to 'O mnie', home_about_path, class: 'btn btn-default' %>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
<h1>Siemano memiczne świry</h1>
<p>Najlepsze skradzione memy z internetu</p>
  <%= link_to 'O mnie', home_about_path, class: 'btn btn-default' %>
  <%= link_to 'Strona główna', root_path, class: 'btn btn-primary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Szytow Memiarnia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/header' %>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>